services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_scraping_dev
      MYSQL_USER: go-scraping-user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306